name: cv
channels:
  - defaults
dependencies:
  - python=3.5.4
  - pip:
    - appnope==0.1.0
    - cycler==0.10.0
    - decorator==4.2.1
    - dlib==19.9.0
    - imutils==0.4.5
    - ipykernel==4.8.2
    - ipython==6.2.1
    - ipython-genutils==0.2.0
    - jedi==0.11.1
    - jupyter-client==5.2.2
    - jupyter-core==4.4.0
    - kiwisolver==1.0.1
    - matplotlib==2.2.0
    - networkx==2.1
    - numpy==1.14.1
    - opencv-contrib-python==3.4.0.12
    - pandas==0.22.0
    - parso==0.1.1
    - pexpect==4.4.0
    - pickleshare==0.7.4
    - pillow==5.0.0
    - prompt-toolkit==1.0.15
    - ptyprocess==0.5.2
    - pygments==2.2.0
    - pyparsing==2.2.0
    - pytesseract==0.2.0
    - python-dateutil==2.6.1
    - python-magic==0.4.15
    - pytz==2018.3
    - pywavelets==0.5.2
    - pyyaml==3.12
    - pyzmq==17.0.0
    - seaborn==0.8.1
    - scikit-image==0.13.1
    - scikit-learn==0.19.1
    - scipy==1.0.0
    - simplegeneric==0.8.1
    - six==1.11.0
    - tornado==5.0
    - tqdm==4.19.6
    - traitlets==4.3.2
    - wcwidth==0.1.7
